// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComMaxp007AvitoTestTaskModels(in *jlexer.Lexer, out *AdvertResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int64(in.Int64())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "pictures":
			if in.IsNull() {
				in.Skip()
				out.Pictures = nil
			} else {
				in.Delim('[')
				if out.Pictures == nil {
					if !in.IsDelim(']') {
						out.Pictures = make([]string, 0, 4)
					} else {
						out.Pictures = []string{}
					}
				} else {
					out.Pictures = (out.Pictures)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Pictures = append(out.Pictures, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "main_photo":
			out.MainPicture = string(in.String())
		case "price":
			out.Price = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComMaxp007AvitoTestTaskModels(out *jwriter.Writer, in AdvertResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Id != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	{
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if len(in.Pictures) != 0 {
		const prefix string = ",\"pictures\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.Pictures {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	if in.MainPicture != "" {
		const prefix string = ",\"main_photo\":"
		out.RawString(prefix)
		out.String(string(in.MainPicture))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdvertResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComMaxp007AvitoTestTaskModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdvertResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComMaxp007AvitoTestTaskModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdvertResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComMaxp007AvitoTestTaskModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdvertResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComMaxp007AvitoTestTaskModels(l, v)
}
func easyjsonD2b7633eDecodeGithubComMaxp007AvitoTestTaskModels1(in *jlexer.Lexer, out *AdvertCreateBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "pictures":
			if in.IsNull() {
				in.Skip()
				out.Pictures = nil
			} else {
				in.Delim('[')
				if out.Pictures == nil {
					if !in.IsDelim(']') {
						out.Pictures = make([]string, 0, 4)
					} else {
						out.Pictures = []string{}
					}
				} else {
					out.Pictures = (out.Pictures)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Pictures = append(out.Pictures, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "price":
			out.Price = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComMaxp007AvitoTestTaskModels1(out *jwriter.Writer, in AdvertCreateBody) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if len(in.Pictures) != 0 {
		const prefix string = ",\"pictures\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.Pictures {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdvertCreateBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComMaxp007AvitoTestTaskModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdvertCreateBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComMaxp007AvitoTestTaskModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdvertCreateBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComMaxp007AvitoTestTaskModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdvertCreateBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComMaxp007AvitoTestTaskModels1(l, v)
}
